apiVersion: v1
kind: Service
metadata:
  name: expense-service
spec:
  selector:
    app: expense
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort  # Ou LoadBalancer si tu es sur un cloud
